services:
  monkey-island-vpn-bot:
    restart: unless-stopped
    network_mode: host
    hostname: monkeyisland.life
    image: monkey-island-vpn-bot:v0.1
    env_file:
      - .env
    privileged: true
    volumes:
      - log:/app/log
      - locales:/app/locales
      - ../../../shredder-action-controll/texts/messages.yml:/app/external/action-control-messages.yml:ro
      - ../../../shredder-action-controll/assets:/app/external/action-control-assets:ro
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  log:
  locales:
