# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from proto import rwmanager_pb2 as proto_dot_rwmanager__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in proto/rwmanager_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RwManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserByUuid = channel.unary_unary(
            "/rwmanager.RwManager/GetUserByUuid",
            request_serializer=proto_dot_rwmanager__pb2.GetUserByUuidRequest.SerializeToString,
            response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
            _registered_method=True,
        )
        self.GetUserByUsername = channel.unary_unary(
            "/rwmanager.RwManager/GetUserByUsername",
            request_serializer=proto_dot_rwmanager__pb2.GetUserByUsernameRequest.SerializeToString,
            response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
            _registered_method=True,
        )
        self.AddUser = channel.unary_unary(
            "/rwmanager.RwManager/AddUser",
            request_serializer=proto_dot_rwmanager__pb2.AddUserRequest.SerializeToString,
            response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
            _registered_method=True,
        )
        self.UpdateUser = channel.unary_unary(
            "/rwmanager.RwManager/UpdateUser",
            request_serializer=proto_dot_rwmanager__pb2.UpdateUserRequest.SerializeToString,
            response_deserializer=proto_dot_rwmanager__pb2.UserResponse.FromString,
            _registered_method=True,
        )
        self.GetAllUsers = channel.unary_unary(
            "/rwmanager.RwManager/GetAllUsers",
            request_serializer=proto_dot_rwmanager__pb2.GetAllUsersRequest.SerializeToString,
            response_deserializer=proto_dot_rwmanager__pb2.GetAllUsersReply.FromString,
            _registered_method=True,
        )
        self.DeleteUser = channel.unary_unary(
            "/rwmanager.RwManager/DeleteUser",
            request_serializer=proto_dot_rwmanager__pb2.DeleteUserRequest.SerializeToString,
            response_deserializer=proto_dot_rwmanager__pb2.DeleteUserResponse.FromString,
            _registered_method=True,
        )
        self.GetInbounds = channel.unary_unary(
            "/rwmanager.RwManager/GetInbounds",
            request_serializer=proto_dot_rwmanager__pb2.Empty.SerializeToString,
            response_deserializer=proto_dot_rwmanager__pb2.GetInboundsResponse.FromString,
            _registered_method=True,
        )


class RwManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserByUuid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetInbounds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RwManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetUserByUuid": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserByUuid,
            request_deserializer=proto_dot_rwmanager__pb2.GetUserByUuidRequest.FromString,
            response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
        ),
        "GetUserByUsername": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserByUsername,
            request_deserializer=proto_dot_rwmanager__pb2.GetUserByUsernameRequest.FromString,
            response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
        ),
        "AddUser": grpc.unary_unary_rpc_method_handler(
            servicer.AddUser,
            request_deserializer=proto_dot_rwmanager__pb2.AddUserRequest.FromString,
            response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
        ),
        "UpdateUser": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateUser,
            request_deserializer=proto_dot_rwmanager__pb2.UpdateUserRequest.FromString,
            response_serializer=proto_dot_rwmanager__pb2.UserResponse.SerializeToString,
        ),
        "GetAllUsers": grpc.unary_unary_rpc_method_handler(
            servicer.GetAllUsers,
            request_deserializer=proto_dot_rwmanager__pb2.GetAllUsersRequest.FromString,
            response_serializer=proto_dot_rwmanager__pb2.GetAllUsersReply.SerializeToString,
        ),
        "DeleteUser": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteUser,
            request_deserializer=proto_dot_rwmanager__pb2.DeleteUserRequest.FromString,
            response_serializer=proto_dot_rwmanager__pb2.DeleteUserResponse.SerializeToString,
        ),
        "GetInbounds": grpc.unary_unary_rpc_method_handler(
            servicer.GetInbounds,
            request_deserializer=proto_dot_rwmanager__pb2.Empty.FromString,
            response_serializer=proto_dot_rwmanager__pb2.GetInboundsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rwmanager.RwManager", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rwmanager.RwManager", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RwManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserByUuid(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rwmanager.RwManager/GetUserByUuid",
            proto_dot_rwmanager__pb2.GetUserByUuidRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserByUsername(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rwmanager.RwManager/GetUserByUsername",
            proto_dot_rwmanager__pb2.GetUserByUsernameRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rwmanager.RwManager/AddUser",
            proto_dot_rwmanager__pb2.AddUserRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rwmanager.RwManager/UpdateUser",
            proto_dot_rwmanager__pb2.UpdateUserRequest.SerializeToString,
            proto_dot_rwmanager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAllUsers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rwmanager.RwManager/GetAllUsers",
            proto_dot_rwmanager__pb2.GetAllUsersRequest.SerializeToString,
            proto_dot_rwmanager__pb2.GetAllUsersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rwmanager.RwManager/DeleteUser",
            proto_dot_rwmanager__pb2.DeleteUserRequest.SerializeToString,
            proto_dot_rwmanager__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetInbounds(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rwmanager.RwManager/GetInbounds",
            proto_dot_rwmanager__pb2.Empty.SerializeToString,
            proto_dot_rwmanager__pb2.GetInboundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
