TELEGRAM_BOT_URL = "https://t.me/SHREDDER_VPN_BOT_PLACEHOLDER"
TELEGRAM_CHANNEL_URL = "https://t.me/SHREDDER_VPN_CHANNEL_PLACEHOLDER"
TELEGRAM_SUPPORT_URL = "https://t.me/zadkie1"
PUBLIC_OFFER_URL = "https://SHREDDER_VPN_PUBLIC_OFFER_PLACEHOLDER"
